# Generated by Django 3.1.3 on 2020-11-23 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovieShot',
            new_name='MovieShots',
        ),
    ]
