# Generated by Django 3.1.1 on 2020-11-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_movie_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
